# Generated by Django 4.2.4 on 2023-12-27 15:19
import blog.models
from blog.models import get_default_author
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='author',
            field=models.ForeignKey(
                default=get_default_author, on_delete=models.CASCADE, to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='author',
            field=models.ForeignKey(
                default=get_default_author, on_delete=models.CASCADE, to=settings.AUTH_USER_MODEL, null=True),
        ),
    ]
