# Generated by Django 4.2.4 on 2024-01-17 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
