# Generated by Django 4.2.4 on 2024-01-19 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0013_authorprofile_first_name_authorprofile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='authorprofile',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
